# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnvNo8vhF_aEAM9Psl7bbKIMsnO89nV-
"""

!pip install tensorflow
!pip install opencv-python
!pip install sklearn

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import cv2 as cv
import pandas as pd
# %matplotlib inline

import math

def sigmoid(x):
  return 1/(1+math.exp(-x))

sigmoid(-345)

def tanh(x):
  return (math.exp(x)-math.exp(-x))/(math.exp(x)+math.exp(-x))

tanh(-234)

def relu(x):
  return max(0,x)

relu(100)

def lrelu(x):
  return max(0.1*x , x)

lrelu(-3)