# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnvNo8vhF_aEAM9Psl7bbKIMsnO89nV-
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
# %matplotlib inline

df = pd.read_csv("/content/cancer-probabilities.csv")

df.head(5)

df.dropna(inplace=True)
df["Smoking Habit"] = df["Smoking Habit"].replace(["Heavy","Occasional","Moderate"],[0,1,2])

df["Smoking Habit"] = df["Smoking Habit"].astype(int)

df["Drinking Habit"] = df["Drinking Habit"].replace(["Frequent","Occasional","Moderate"],[0,1,2])
df["Drinking Habit"] = df["Drinking Habit"].astype(int)

df.head(10)

from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(df[["Smoking Habit","Drinking Habit"]],df["Probability of Cancer"],test_size=0.2)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train,y_train)

model.score(X_test,y_test)

y_predicted = model.predict(X_test)

from sklearn.metrics import mean_absolute_error , mean_squared_error

mean_absolute_error(y_test,y_predicted)

mean_squared_error(y_test,y_predicted)

model.predict([[0 ,1]])