# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnvNo8vhF_aEAM9Psl7bbKIMsnO89nV-
"""

!pip install tensorflow
!pip install opencv-python
!pip install sklearn

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import cv2 as cv
import pandas as pd
# %matplotlib inline

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

iris = load_iris()

dir(iris)

from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(iris.data,iris.target,test_size=0.2)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train,y_train)

model.score(X_test,y_test)

model.predict([X_test[0]])

y_test[0]

len(y_test)

y_pred = model.predict(X_test)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_pred)

import seaborn as sn


sn.heatmap(cm,annot=True)
plt.xlabel("Prediction")
plt.ylabel("Truth")

plt.show()

from sklearn.metrics import mean_squared_error , mean_absolute_error

mse = mean_squared_error(y_test,y_pred)

mse

mae = mean_absolute_error(y_test,y_pred)
mae