# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnvNo8vhF_aEAM9Psl7bbKIMsnO89nV-
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
# %matplotlib inline

df = pd.read_csv("/content/Social_Network_Ads.csv")
df["Gender"] = df["Gender"].replace(["Male","Female"],[0,1])
df.head(10)

from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(df[["Gender","Age","EstimatedSalary"]],df["Purchased"],test_size=0.2)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train,y_train)

model.score(X_test,y_test)

y_predicted = model.predict(X_test)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_predicted)

import seaborn as sn


sn.heatmap(cm,annot=True)
plt.xlabel("Predicted")
plt.ylabel("Truth")
plt.show()

y_test.value_counts()

model.predict([[1,30,40000]])